routes/web.php
<?php


Auth::routes();

Route::namespace('user')->group(function () {

    Route::get('/', 'homeController@index')->name('user.home');

    Route::group(['prefix' => 'travel', 'as' => 'travel.'], function () {
        Route::get('/', 'travelController@index')->name('index');


    });

    Route::group(['prefix' => 'pesan', 'as' => 'pesan.'], function () {
        Route::get('/', 'pesanController@index')->name('index');


    });
});


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/user/homeController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class homeController extends Controller{

    public function index(){
        return view('user/home/index');

    }

    public function create(){
        

    }

    public function store(Request $request){
        

    }

    public function show($id){
        

    }

    public function edit($id){
        

    }

    public function update(Request $request, $id){
        

    }

    public function destroy($id){
        

    }
}

app/Http/Controllers/user/pesanController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class pesanController extends Controller{
 
    public function index(){

        return view('user/pesan/index');

    }

    public function create(){
        

    }

    public function store(Request $request){
        
    }

    public function show($id){
        
    }

    public function edit($id){
        
    }

    public function update(Request $request, $id){
        
    }

    public function destroy($id){
        
        
    }
}

app/Http/Controllers/user/travelController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class travelController extends Controller{

    public function index(){
        return view('user/travel/index');

    }

    public function create(){
        

    }

    public function store(Request $request){
        

    }

    public function show($id){
        

    }

    public function edit($id){
        

    }

    public function update(Request $request, $id){
        

    }

    public function destroy($id){
        

    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/user/layouts/app.blade.php
<!DOCTYPE HTML>
<html lang="zxx">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Antarin</title>
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/bootstrap.min.css')}}" media="all" />
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/slicknav.min.css')}}" media="all" />
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/icofont.css')}}" media="all" />
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/slick.css')}}">
	<link rel="stylesheet" href="{{asset('assets/css/font-awesome.min.css')}}">
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/owl.carousel.css')}}">
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/magnific-popup.css')}}">
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/switcher-style.css')}}">
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/animate.min.css')}}">
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/style.css')}}" media="all" />
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/fontawesome/css/all.css')}}" media="all" />
	<link rel="stylesheet" type="text/css" href="{{asset('assets/css/responsive.css')}}" media="all" />
	<link rel="icon" type="image/png" href="{{asset('assets/img/favcion.png')}}" />
</head>
@yield('extrahead')
<body data-spy="scroll" data-target=".header" data-offset="50">
	<div id="preloader"></div>
	<header class="header">
		<div class="container">
			<div class="row flexbox-center">
				<div class="col-lg-2 col-md-3 col-6">
					<div class="logo">
						<a href="#home"><img src="assets/img/logo.png" alt="logo" /></a>
					</div>
				</div>
				<div class="col-lg-10 col-md-9 col-6">
					<div class="responsive-menu"></div>
					<div class="mainmenu">
                        <ul id="primary-menu">
                            <li><a class="nav-link active" href="{{route('user.home')}}">Home</a></li>
                            <li><a class="nav-link" href="{{route('travel.index')}}">Travel</a></li>
                            <li><a class="nav-link" href="{{route('pesan.index')}}">Pesan Travel</a></li>
                            <li><a class="nav-link" href="">Pesan</a></li>
                        	<li><a class="appao-btn" href="#">Login / Daftar</a></li>
                    	</ul>
					</div>
				</div>
			</div>
		</div>
	</header>
	@yield('content')
	<footer class="footer" id="contact">
		<div class="container">
			<div class="row">
            	<div class="col-lg-6">
					<div class="contact-form">
						<h4>Get in Touch</h4>
						<p class="form-message"></p>
						<form id="contact-form" action="#" method="POST">
				        	<input type="text" name="name" placeholder="Enter Your Name">
				            <input type="email" name="email" placeholder="Enter Your Email">
				            <input type="text" name="subject" placeholder="Your Subject">
				            <textarea placeholder="Messege" name="message"></textarea>
				            <button type="submit" name="submit">Send Message</button>
				        </form>
					</div>
                </div>
                <div class="col-lg-6">
					<div class="contact-address">
						<h4>Address</h4>
						<p>Jl. Udang Windu 60, Kabupaten Jember</p>
						<ul>
							<li>
								<div class="contact-address-icon">
									<i class="icofont icofont-headphone-alt"></i>
								</div>
								<div class="contact-address-info">
									<a href="callto:#">+6281259902612</a>
									<a href="callto:#">+6289623834328</a>
								</div>
							</li>
							<li>
								<div class="contact-address-icon">
									<i class="icofont icofont-envelope"></i>
								</div>
								<div class="contact-address-info">
									<a href="mailto:antar.instartup@gmail.com">antar.instartup@gmail.com</a>
								</div>
							</li>
							<li>
								<div class="contact-address-icon">
									<i class="icofont icofont-web"></i>
								</div>
								<div class="contact-address-info">
									<a href="www.antarin.com">www.antarin.com</a>
								</div>
							</li>
						</ul>
					</div>
                </div>
			</div>
			<div class="row">
                <div class="col-lg-12">
					<div class="copyright-area">
						<ul>
							<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#"><i class="fab fa-instagram"></i></a></li>
							<li><a href="#"><i class="fab fa-twitter"></i></a></li>
						</ul>
					</div>
                </div>
			</div>
		</div>
	</footer>
	<a href="#" class="scrollToTop">
		<i class="icofont icofont-arrow-up"></i>
	</a>
	<script src="{{asset('assets/js/jquery.min.js')}}"></script>
	<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>
	<script src="{{asset('assets/js/jquery.slicknav.min.js')}}"></script>
	<script src="{{asset('assets/js/slick.min.js')}}"></script>
	<script src="{{asset('assets/js/owl.carousel.min.js')}}"></script>
	<script src="{{asset('assets/js/jquery.magnific-popup.min.js')}}"></script>
	<script src="{{asset('assets/js/jquery.counterup.min.js')}}"></script>
	<script src="{{asset('assets/js/waypoints.min.js')}}"></script>
	<script src="{{asset('assets/js/jquery.mb.YTPlayer.min.js')}}"></script>
	<script src="{{asset('assets/js/jquery.easing.1.3.js')}}"></script>
	<script src="{{asset('assets/js/gmap3.min.js')}}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBnKyOpsNq-vWYtrwayN3BkF3b4k3O9A_A"></script>
	<script src="{{asset('assets/js/custom-map.js')}}"></script>
	<script src="{{asset('assets/js/wow-1.3.0.min.js')}}"></script>
	<script src="{{asset('assets/js/switcher.js')}}"></script>
	<script src="{{asset('assets/js/main.js')}}"></script>
</body>
</html>

resources/views/user/pesan/index.blade.php
@extends('user.layouts.app')
@section('content')
<section class="hero-area" id="home">
    <div class="container">
        <div class="row">
		    <div class="col-lg-7">
                <div class="hero-area-content">
				    <h1>Pesan Sekarang !!</h1>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo </p>
					<a href="#" class="appao-btn">Google Play</a>
					<a href="#" class="appao-btn">App Store</a>
                </div>
			</div>
			<div class="col-lg-5">
                <div class="hand-mockup text-lg-left text-center">
					<img src="{{asset('assets/img/preview.png')}}" alt="Hand Mockup" />
                </div>
			</div>
        </div>
	</div>
</section>
<section class="about-area ptb-90">
	<div class="container">
        <div class="row">
			<div class="col-lg-12">
				<div class="sec-title">
					<h2>Pesan Travel<span class="sec-title-border"><span></span><span></span><span></span></span></h2>
					<p>Silahkan isi ketentuan di bawah ini !!</p>
                </div>
			</div>
        </div>
        <div class="row">
            <div class="col">
                <select class="form-control form-control-lg">
                    <option>Pilih Lokasi Penjemputan</option>
                </select>
            </div>
            <div class="col">
                <select class="form-control form-control-lg">
                    <option>Pilih Tujuan Akhir</option>
                </select>
            </div>
            <div class="col">
                <button type="button" class="btn btn-primary btn-lg btn-block">Submit</button>
            </div>
        </div>
	</div>
</section>
<div class="google-map"></div>
@endsection

resources/views/user/travel/index.blade.php
@extends('user.layouts.app')
@section('content')
<section class="hero-area" id="home">
    <div class="container">
        <div class="row">
		    <div class="col-lg-7">
                <div class="hero-area-content">
				    <h1>Our Mitra Travel</h1>
				    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo </p>
					<a href="#" class="appao-btn">Google Play</a>
					<a href="#" class="appao-btn">App Store</a>
                </div>
			</div>
			<div class="col-lg-5">
                <div class="hand-mockup text-lg-left text-center">
				    <img src="{{asset('assets/img/preview.png')}}" alt="Hand Mockup" />
                </div>
			</div>
        </div>
	</div>
</section>
<section class="team-area ptb-90" id="team">
	<div class="container">
        <div class="row">
			<div class="col-lg-12">
				<div class="sec-title">
					<h2>Daftar Mitra<span class="sec-title-border"><span></span><span></span><span></span></span></h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
                </div>
			</div>
        </div>
        <div class="row">
			<div class="col-lg-3 col-sm-3">
				<div class="single-team-member">
					<div class="team-member-img">
                        <img src="{{asset('assets/img/team/hafiz.jpeg')}}" alt="team">
                        <div class="team-member-icon">
							<div class="display-table">
                                <div class="display-tablecell">
									<a href="#"><i class="fab fa-facebook-f"></i></a>
									<a href="#"><i class="fab fa-instagram"></i></a>
									<a href="#"><i class="fab fa-twitter"></i></a>>
                                </div>
							</div>
                        </div>
					</div>
					<div class="team-member-info">
                        <a href="#"><h4>Hafiz</h4></a>
                        <!-- <p>UX Designer</p> -->
					</div>
                </div>
			</div>
			<div class="col-lg-3 col-sm-3">
				<div class="single-team-member">
					<div class="team-member-img">
                        <img src="{{asset('assets/img/team/anas.jpeg')}}" alt="team">
                        <div class="team-member-icon">
							<div class="display-table">
                                <div class="display-tablecell">
									<a href="#"><i class="fab fa-facebook-f"></i></a>
									<a href="#"><i class="fab fa-instagram"></i></a>
									<a href="#"><i class="fab fa-twitter"></i></a>
                                </div>
							</div>
                        </div>
					</div>
					<div class="team-member-info">
                        <a href="#"><h4>Anas</h4></a>
                        <!-- <p>UX Designer</p> -->
					</div>
                </div>
			</div>
			<div class="col-lg-3 col-sm-3">
				<div class="single-team-member">
					<div class="team-member-img">
                        <img src="{{asset('assets/img/team/ihul.jpeg')}}" alt="team">
                        <div class="team-member-icon">
							<div class="display-table">
                                <div class="display-tablecell">
									<a href="#"><i class="fab fa-facebook-f"></i></a>
									<a href="#"><i class="fab fa-instagram"></i></a>
									<a href="#"><i class="fab fa-twitter"></i></a>
                                </div>
							</div>
                        </div>
					</div>
					<div class="team-member-info">
                        <a href="#"><h4>Ihul</h4></a>
                        <!-- <p>UX Designer</p> -->
					</div>
                </div>
			</div>
            <div class="col-lg-3 col-sm-3">
				<div class="single-team-member">
					<div class="team-member-img">
                        <img src="{{asset('assets/img/team/ihul.jpeg')}}" alt="team">
                        <div class="team-member-icon">
							<div class="display-table">
                                <div class="display-tablecell">
									<a href="#"><i class="fab fa-facebook-f"></i></a>
									<a href="#"><i class="fab fa-instagram"></i></a>
									<a href="#"><i class="fab fa-twitter"></i></a>
                                </div>
							</div>
                        </div>
					</div>
					<div class="team-member-info">
                        <a href="#"><h4>Ihul</h4></a>
                        <!-- <p>UX Designer</p> -->
					</div>
                </div>
			</div>
        </div>
	</div>
</section>
<!-- <section class="blog-area ptb-90" id="blog">
	<div class="container">
        <div class="row">
			<div class="col-lg-12">
				<div class="sec-title">
					<h2>Our Latest Blog<span class="sec-title-border"><span></span><span></span><span></span></span></h2>
					<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt </p>
                </div>
			</div>
        </div>
        <div class="row">
			<div class="col-lg-4 col-md-6">
				<div class="single-post">
					<div class="post-thumbnail">
                        <a href="blog.html"><img src="assets/img/blog/blog1.jpg" alt="blog"></a>
					</div>
					<div class="post-details">
                        <div class="post-author">
							<a href="blog.html"><i class="icofont icofont-user"></i>John</a>
							<a href="blog.html"><i class="icofont icofont-speech-comments"></i>Comments</a>
							<a href="blog.html"><i class="icofont icofont-calendar"></i>21 Feb 2018</a>
                        </div>
                        <h4 class="post-title"><a href="blog.html">Lorem ipsum dolor sit</a></h4>
                        <p>Lorem ipsum dolor sit amet, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad</p>
					</div>
                </div>
			</div>
			<div class="col-lg-4 col-md-6">
				<div class="single-post">
					<div class="post-thumbnail">
                        <a href="blog.html"><img src="{{asset('assets/img/blog/blog2.jpg')}}" alt="blog"></a>
					</div>
					<div class="post-details">
                        <div class="post-author">
							<a href="blog.html"><i class="icofont icofont-user"></i>John</a>
							<a href="blog.html"><i class="icofont icofont-speech-comments"></i>Comments</a>
							<a href="blog.html"><i class="icofont icofont-calendar"></i>21 Feb 2018</a>
                        </div>
                        <h4 class="post-title"><a href="blog.html">Lorem ipsum dolor sit</a></h4>
                        <p>Lorem ipsum dolor sit amet, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad</p>
					</div>
                </div>
			</div>
			<div class="col-lg-4 d-md-none d-lg-block">
				<div class="single-post">
					<div class="post-thumbnail">
                        <a href="blog.html"><img src="{{asset('assets/img/blog/blog3.jpg')}}" alt="blog"></a>
					</div>
					<div class="post-details">
                        <div class="post-author">
							<a href="blog.html"><i class="icofont icofont-user"></i>John</a>
							<a href="blog.html"><i class="icofont icofont-speech-comments"></i>Comments</a>
							<a href="blog.html"><i class="icofont icofont-calendar"></i>21 Feb 2018</a>
                        </div>
                        <h4 class="post-title"><a href="blog.html">Lorem ipsum dolor sit</a></h4>
                        <p>Lorem ipsum dolor sit amet, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad</p>
					</div>
                </div>
			</div>
        </div>
	</div>
</section> -->
<div class="google-map"></div>
@endsection